# 只支持 16:9!!! 
# 1920 * 1080
# 2560 * 1440
# 3840 * 2160

tech:
# 技术中心
  - [沙暴垂直补偿器, -1]
work:
# 工作台
  - [9x39mm BP, -1]
medical:
# 制药台
  - [OE2战斗兴奋剂, -1]
armor:
# 防具台
  - [精英防弹背心, -1]

# 高级设置
TESSERACT_PATH: .\dist\Tesseract-OCR\tesseract.exe
background_mode: false
debug_mode: false
